[settings]
activate_aggressive = true
experimental = true
lockfile = true

[tools]
actionlint = "latest"
hk = "latest"
packer = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
tart = "latest"
tombi = "latest"
usage = "latest"

[hooks]
postinstall = "mise run bootstrap"

# Tasks

[tasks.bootstrap]
run = ["hk install --mise", { task = "_bootstrap_hk" }]

[tasks.check]
alias = ["chk", "lint"]
run = "hk check --all"

[tasks.fix]
alias = ["fmt", "format"]
run = "hk fix --all"

[tasks.upd]
run = ["mise upgrade", "mise lock"]

[tasks.upg]
run = ["mise upgrade --bump", "mise lock"]

# Hidden Tasks

[tasks._bootstrap_hk]
hide = true
run = "scripts/update-hk-import.bash"
sources = ["hk.pkl", "mise.lock", "mise.toml", "scripts/update-hk-import.bash"]
outputs = { auto = true }
