# The minimum version of Mise that is required to run this project.
min_version = "2025.6.0"

[settings]
experimental = true

[tools]
"aqua:cirruslabs/tart" = "latest"
"aqua:XcodesOrg/xcodes" = "latest"
jq = "latest"
packer = "latest"
usage = "latest"
