---
- name: Create temp directory for certificates
  ansible.builtin.tempfile:
    state: directory
    suffix: certs
  register: xcode_cert_tmpdir

- name: Download Apple WWDR CA G3 certificate
  ansible.builtin.get_url:
    url: https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer
    dest: "{{ xcode_cert_tmpdir.path }}/AppleWWDRCAG3.cer"
    mode: "0644"

- name: Download Developer ID G2 CA certificate
  ansible.builtin.get_url:
    url: https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer
    dest: "{{ xcode_cert_tmpdir.path }}/DeveloperIDG2CA.cer"
    mode: "0644"

- name: Import certificates into system keychain
  ansible.builtin.command:
    cmd: security import {{ item }} -k /Library/Keychains/System.keychain
  become: true
  changed_when: true
  loop:
    - "{{ xcode_cert_tmpdir.path }}/AppleWWDRCAG3.cer"
    - "{{ xcode_cert_tmpdir.path }}/DeveloperIDG2CA.cer"

- name: Remove certificate temp directory
  ansible.builtin.file:
    path: "{{ xcode_cert_tmpdir.path }}"
    state: absent
