---
- name: Copy xcode-utils library to remote
  ansible.builtin.copy:
    src: "{{ role_path }}/../../../../scripts/xcode/lib/xcode-utils.bash"
    dest: /tmp/xcode-utils.bash
    mode: "0644"

- name: Install cached Xcode versions
  ansible.builtin.script:
    cmd: >-
      {{ role_path }}/../../../../scripts/xcode/install-cached-xcode-versions.bash {{ xcode_cache_dir }} {{ xcode_default_version }}
  become: true
  changed_when: true

- name: Remove xcode-utils from temp
  ansible.builtin.file:
    path: /tmp/xcode-utils.bash
    state: absent
