---
- name: Configure Xcode preferences
  ansible.builtin.import_tasks: configure.yml

- name: Install developer certificates
  ansible.builtin.import_tasks: certificates.yml

- name: Install cached Xcode versions
  ansible.builtin.import_tasks: install.yml

- name: Install simulator runtimes
  ansible.builtin.import_tasks: simruntimes.yml

- name: Create simulators
  ansible.builtin.import_tasks: simulators.yml

- name: Prewarm simulators
  ansible.builtin.import_tasks: prewarm.yml
