---
- name: Find Apple SDK .dmg files in local cache
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/../../.cache/simruntime"
    patterns: "*.dmg"
  delegate_to: localhost
  become: false
  register: xcode_sdk_files

- name: Select Apple SDK .dmg files to install
  ansible.builtin.set_fact:
    xcode_selected_sdk_files: []

- name: Build Apple SDK .dmg selection list
  ansible.builtin.set_fact:
    xcode_selected_sdk_files: "{{ xcode_selected_sdk_files + [item] }}"
  loop: "{{ xcode_sdk_files.files }}"
  when: (xcode_cache_sdk_dmg_files | length == 0) or ((item.path | basename) in xcode_cache_sdk_dmg_files)

- name: Install Apple SDKs from cache
  when: xcode_selected_sdk_files | length > 0
  block:
    - name: Create temp directory for SDK cache on remote
      ansible.builtin.tempfile:
        state: directory
        suffix: sdk_cache
      register: xcode_sdk_tmpdir

    - name: Copy Apple SDK .dmg files to remote
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ xcode_sdk_tmpdir.path }}/"
        mode: "0644"
      loop: "{{ xcode_selected_sdk_files }}"

    - name: Install Apple SDKs
      ansible.builtin.command:
        cmd: xcrun simctl runtime add {{ xcode_sdk_tmpdir.path }}/{{ item.path | basename }}
      become: true
      changed_when: true
      loop: "{{ xcode_selected_sdk_files }}"

    - name: Remove SDK cache from remote
      ansible.builtin.file:
        path: "{{ xcode_sdk_tmpdir.path }}"
        state: absent
