---
# todo: add idempotency to check if admin user already has auto-login enabled
- name: Enable auto-login for admin user
  ansible.builtin.script: enable-auto-login.bash
  environment:
    USERNAME: "{{ macos_admin_user }}"
    PASSWORD: "{{ macos_admin_password }}"
  become: true
  changed_when: true
