---
- name: Install Xcode Command Line Tools
  hosts: macos_agents
  gather_facts: false
  roles:
    - role: xcode_clt

- name: Install Rosetta 2
  hosts: macos_agents
  roles:
    - role: rosetta

- name: Configure SSH known hosts
  hosts: macos_agents
  roles:
    - role: ssh_config

- name: Configure system settings
  hosts: macos_agents
  roles:
    - role: system_config

- name: Install macOS updates
  hosts: macos_agents
  roles:
    - role: macos_updates
