---
- name: Print software update cache notice
  ansible.builtin.debug:
    msg: Fetching software update catalog — this may take a minute...

- name: Create Command Line Tools installation trigger file
  ansible.builtin.raw: touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  become: true
  changed_when: false

- name: Cache software update catalog
  ansible.builtin.raw: softwareupdate --list --include-config-data
  become: true
  changed_when: false
  timeout: 120
