---
- name: Configure system preferences
  ansible.builtin.import_tasks: preferences.yml

- name: Configure power management
  ansible.builtin.import_tasks: power.yml

- name: Configure user shell
  ansible.builtin.import_tasks: shell.yml

- name: Update Safari
  ansible.builtin.import_tasks: safari.yml

- name: Check SIP status
  ansible.builtin.command:
    cmd: csrutil status
  register: system_config_csrutil_status
  changed_when: false

- name: Set SIP disabled fact
  ansible.builtin.set_fact:
    system_config_sip_disabled: "{{ 'disabled' in system_config_csrutil_status.stdout }}"
  changed_when: false

- name: Disable protected services
  ansible.builtin.include_tasks: services.yml
  when: system_config_sip_disabled

- name: Configure Gatekeeper
  ansible.builtin.include_tasks: gatekeeper.yml
  when: system_config_sip_disabled
