---
- name: Disable automatic update check
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: false
  become: true

- name: Check for available updates
  ansible.builtin.command: softwareupdate --all --list
  register: macos_updates_swupdate_list
  changed_when: false
  failed_when: false

- name: Parse available updates
  ansible.builtin.set_fact:
    macos_updates_available_updates: >-
      {{ macos_updates_swupdate_list.stdout
         | regex_findall('\* Label: (.*)\n\tTitle: (.*), Version: (.*), Size: (.*), Recommended: (.*), Action: (.*),')
         | map('zip', ['label', 'title', 'version', 'size', 'recommended', 'action'])
         | map('map', 'reverse')
         | map('community.general.dict')
         | list }}

- name: Print available updates
  ansible.builtin.debug:
    var: macos_updates_available_updates

- name: Install available updates
  ansible.builtin.command:
    cmd: "softwareupdate --install --agree-to-license --force --restart --user {{ macos_admin_user }} --stdinpass '{{ item.label }}'"
    stdin: "{{ macos_admin_password }}"
  changed_when: macos_updates_swupdate_install.rc == 0
  become: true
  register: macos_updates_swupdate_install
  ignore_unreachable: true
  ignore_errors: true
  loop: "{{ macos_updates_available_updates }}"
  when: >-
    not item.label.startswith('macOS') or item.version.split('.')[0] == ansible_facts['distribution_version'].split('.')[0]

- name: Wait for VM to come back after update
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 1800
  when: macos_updates_available_updates | length > 0
