---
macos_admin_user: admin
macos_admin_password: admin

ansible_become_password: "{{ macos_admin_password }}"
ansible_connection: ssh
ansible_user: "{{ macos_admin_user }}"
ansible_password: "{{ macos_admin_password }}"
ansible_ssh_password_mechanism: ssh_askpass

xcode_install_enabled: true
macos_update_enabled: true

# Homebrew

homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  - bash
  - curl
  - dockutil
  - git
  - git-lfs
  - mise
  - python
  - unxip
  - xcodes

# Dock

dockitems_apps:
  - name: Safari
    path: /Applications/Safari.app/
  - name: Terminal
    path: /System/Applications/Utilities/Terminal.app/
  - name: System Settings
    path: /System/Applications/System Settings.app/

dockitems_folders:
  - name: Applications
    path: /Applications/
  - name: Downloads
    path: ~/Downloads
