---
macos_admin_user: admin
macos_admin_password: admin

ansible_become_password: "{{ macos_admin_password }}"
ansible_connection: ssh
ansible_user: "{{ macos_admin_user }}"
ansible_password: "{{ macos_admin_password }}"
ansible_ssh_password_mechanism: ssh_askpass

xcode_install_enabled: true
macos_update_enabled: true

# Xcode

# Xcode .xip files must be pre-staged in the admin user's Downloads folder before provisioning.
xcode_default_version: "26.5.0"
xcode_simruntime_downloads:
  - build_version: "26.0.1"
    architecture_variant: arm64
  - build_version: "26.5"
    architecture_variant: arm64
xcode_simulators:
  - name: "iPhone 17"
    device_type: "iPhone 17"
    runtime: "com.apple.CoreSimulator.SimRuntime.iOS-26-0"
  - name: "iPhone 17"
    device_type: "iPhone 17"
    runtime: "com.apple.CoreSimulator.SimRuntime.iOS-26-5"

# Homebrew

homebrew_upgrade_all_packages: true

homebrew_taps:
  - openai/tools

homebrew_installed_packages:
  - bash
  - curl
  - dockutil
  - git
  - git-lfs
  - mise
  - python
  - tart-guest-agent
  - unxip
  - xcodes

# Dock

dockitems_apps:
  - name: Safari
    path: /Applications/Safari.app/
  - name: Terminal
    path: /System/Applications/Utilities/Terminal.app/
  - name: System Settings
    path: /System/Applications/System Settings.app/

dockitems_folders:
  - name: Applications
    path: /Applications/
  - name: Downloads
    path: ~/Downloads
