---
macos_admin_user: admin
macos_admin_password: admin

ansible_connection: ssh
ansible_user: "{{ macos_admin_user }}"
ansible_password: "{{ macos_admin_password }}"
ansible_ssh_password_mechanism: ssh_askpass

# Homebrew

homebrew_taps:
  - cirruslabs/cli

homebrew_base_packages:
  - bash
  - curl
  - git
  - mise
  - python
  - xcodes

# Dock

dockitems_remove:
  - App Store
  - Apps
  - Calendar
  - Contacts
  - FaceTime
  - Freeform
  - Games
  - iPhone Mirroring
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Phone
  - Photos
  - Reminders
  - TV

dockitems_persist:
  - name: Safari
    path: /Applications/Safari.app/
  - name: Terminal
    path: /System/Applications/Utilities/Terminal.app/
  - name: System Settings
    path: /System/Applications/System Settings.app/
  - name: Downloads
    path: ~/Downloads
