---
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
env:
  MISE_ENV: ci
  MISE_LOCKED: 1

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - name: checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: cache Ansible dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |-
            galaxy_collection
            galaxy_roles
          key: ${{ runner.os }}-${{ hashFiles('ansible.cfg', 'requirements.yml') }}

      - name: setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: run linters
        run: mise run chk
