---
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
env:
  MISE_ENV: ci

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - name: install zsh
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends zsh

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - run: mise run chk
